LLM first transformers UT
intel-analytics/BigDL pull request #8514
Opened 2023-07-13 06:58 UTC by Litchilitchy

## Description
LLM first transformers UT

2023-07-13 07:09 UTC, Oscilloscope98 approved these changes
Others LGTM. Let's wait for the UT to pass

2023-07-13 07:09 UTC, Oscilloscope98 commented on python/llm/test/inference/test_transformers_api.py
> +from bigdl.llm.utils import get_avx_flags
No need for these two lines of imports

2023-07-13 07:27 UTC, Oscilloscope98 requested changes
Let's fix the error in UT

2023-07-19 09:43 UTC, shane-huang approved these changes
This one LGTM.

2023-07-19 09:43 UTC, shane-huang commented on python/llm/test/inference/test_transformers_api.py
> +
later you can submit more PRs to add Seq2Seq model and whisper.

2023-07-20 02:14 UTC, Oscilloscope98 commented
Merge for now. Will raise an PR to and some small fixes

2023-07-20 02:16 UTC, Oscilloscope98 approved these changes

2023-07-20 02:16 UTC, merged